Main page UI
gsidnick/ecommerce-application pull request #20
Opened 2023-08-13 10:10 UTC by deep-logic2000

### Describe your changes
- develop header
- develop navigation menu with routing
- add empty pages connected with navigation manu
- add main slider
### Issue ticket number and link
This PR closes #18 
### Checklist before requesting a review
- [x] Centralized Navigation 🌐
- [x]  Routing Implementation 🚦
- [x]  Evaluation Criteria for Header 🎯

### How has this been tested?
npm run lint and login testpage

2023-08-13 11:05 UTC, ToLive requested changes
Also NextJS has a type for pages: NextPage, instead of ReactElement

2023-08-13 11:35 UTC, ToLive approved these changes

2023-08-13 11:38 UTC, gsidnick approved these changes
Checked!

2023-08-13 11:44 UTC, merged

2023-09-22 14:37 UTC, deep-logic2000 commented on src/components/header/menu/menyData.ts
Done